### ISSUE TITLE
Files are not deleted when ConsulAgentProcess.stop() is called.

### ISSUE THREAD

**Issue by DerDerbste** [golovnin/embedded-consul#1]
I'm running embedded consul in a spring integration test. Everything works fine until i call the stop method on the ConsulAgentProcess instance. 
I get the following error first:

`2018-09-05 15:28:37.073  WARN 13528 --- [           main] d.f.embed.process.io.file.Files          : could not delete C:\Users\XXX\AppData\Local\Temp\extract-4890cd40-3346-428a-bf2e-daaf3a6f1e8aconsul.exe. Will try to delete it again when program exits.
`

After that i get: 

`Exception in thread "Thread-8" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
        at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at de.flapdoodle.embed.process.io.file.FileCleaner.forceDeleteOnExit(FileCleaner.java:52)
	at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:125)
	at de.flapdoodle.embed.process.extract.ExtractedFileSets.delete(ExtractedFileSets.java:77)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.removeFileSet(ExtractedArtifactStore.java:147)
	at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:77)
	at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:90)
	at java.lang.Thread.run(Thread.java:745)
`

When trying to start the test again, the following exception is thrown:

`java.io.IOException: Could not start process: <EOF>
	at com.github.golovnin.embedded.consul.ConsulAgentProcess.onAfterProcessStart(ConsulAgentProcess.java:159)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114)
	at com.github.golovnin.embedded.consul.ConsulAgentProcess.<init>(ConsulAgentProcess.java:76)
	at com.github.golovnin.embedded.consul.ConsulAgentExecutable.start(ConsulAgentExecutable.java:58)
	at com.github.golovnin.embedded.consul.ConsulAgentExecutable.start(ConsulAgentExecutable.java:43)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
	at net.xxx(IntegrationTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

**Comment by golovnin** [comment]
Hi @DerDerbste,
thank you for reporting this problem! I have fixed it in Embedded Consul 1.2.3.0. The new version is already published on JCenter.
